// index.js
export const servicesData = [
  {
    title: "FullStack Development",
    description:
      "Your business deserves a fast, secure, and future-proof digital foundation. I develop custom web apps with clean architecture, optimized databases, and seamless integrations—ensuring reliability at every layer.",
    items: [
      {
        title: "Backend Engineering",
        description: "(REST/GraphQL APIs, Microservices, Auth Systems)",
      },
      {
        title: "Frontend Excellence",
        description: "(React, Vue, TypeScript, Interactive UI/UX)",
      },
      {
        title: "Database Design",
        description: "(SQL/NoSQL Optimization, Scalable Structures)",
      },
    ],
  },
  {
    title: "Security & Optimization",
    description:
      "Slow or hacked apps destroy trust. I harden security (XSS/SQLI protection, OAuth) and optimize bottlenecks so your app stays fast, safe, and scalable as you grow.",
    items: [
      {
        title: "Code Audits",
        description: "(Refactoring, Tech Debt Cleanup)",
      },
      {
        title: "Pen Testing",
        description: "(Vulnerability Assessments)",
      },
      {
        title: "SEO Tech Stack",
        description: "(SSR, Metadata, Structured Data)",
      },
    ],
  },
  {
    title: "Web & Mobile Apps",
    description:
      "A clunky interface can sink even the best ideas. I craft responsive, pixel perfect web and mobile apps (React Native) that users love—bridging design and functionality seamlessly.",
    items: [
      {
        title: "Cross-Platform Apps",
        description: "(Single codebase for iOS/Android/Web)",
      },
      {
        title: "PWAs",
        description: "(Offline mode, Push Notifications)",
      },
      {
        title: "E-Commerce",
        description: "(Checkout flows, Payment Gateways, Inventory APIs)",
      },
    ],
  },
];
export const skillCategories = [
  {
    title: "Languages",
    subtitle: "Typed, scripted, and query languages I work in daily",
    skills: [
      { name: "TypeScript", icon: "logos:typescript-icon" },
      { name: "JavaScript", icon: "logos:javascript" },
      { name: "Python", icon: "logos:python" },
      { name: "SQL", icon: "mdi:database", iconClassName: "text-white" },
      { name: "Lua", icon: "logos:lua" },
    ],
  },
  {
    title: "Frontend",
    subtitle: "Production UI stacks, state, forms, and rich editors",
    skills: [
      { name: "React.js", icon: "logos:react" },
      { name: "Next.js", icon: "skill-icons:nextjs-light" },
      { name: "React Native", icon: "tabler:brand-react-native" },
      { name: "Astro", icon: "logos:astro-icon" },
      { name: "Vite", icon: "logos:vitejs" },
      { name: "Redux Toolkit", icon: "logos:redux" },
      { name: "Zustand", icon: "twemoji:bear" },
      { name: "Tailwind CSS", icon: "logos:tailwindcss-icon" },
      {
        name: "shadcn/ui",
        icon: "simple-icons:shadcnui",
        iconClassName: "text-white",
      },
      {
        name: "Radix UI",
        icon: "simple-icons:radixui",
        iconClassName: "text-white",
      },
      { name: "Framer Motion", icon: "logos:framer" },
      { name: "React Hook Form", icon: "simple-icons:reacthookform" },
      { name: "Zod", icon: "simple-icons:zod" },
      { name: "TanStack Table", icon: "simple-icons:tanstack" },
      { name: "TipTap", icon: "mdi:format-text", iconClassName: "text-white" },
      {
        name: "BlockNote",
        icon: "mdi:note-text-outline",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Backend",
    subtitle: "APIs, ORMs, and migrations across Node and Python",
    skills: [
      { name: "Node.js", icon: "logos:nodejs-icon" },
      {
        name: "Express.js",
        icon: "simple-icons:express",
        iconClassName: "text-white",
      },
      { name: "Django", icon: "logos:django-icon" },
      {
        name: "Django REST Framework",
        icon: "simple-icons:django",
        iconClassName: "text-white",
      },
      { name: "FastAPI", icon: "logos:fastapi-icon" },
      {
        name: "Django Channels",
        icon: "mdi:broadcast",
        iconClassName: "text-white",
      },
      { name: "Drizzle ORM", icon: "simple-icons:drizzle" },
      {
        name: "Alembic",
        icon: "mdi:flask-outline",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "AI / LLM / ML",
    subtitle: "LLM APIs, RAG pipelines, and prompt engineering in production",
    skills: [
      {
        name: "OpenAI API",
        icon: "simple-icons:openai",
        iconClassName: "text-white",
      },
      { name: "Google Gemini", icon: "logos:google-gemini" },
      { name: "Anthropic Claude", icon: "logos:claude" },
      {
        name: "Fal AI",
        icon: "mdi:image-multiple-outline",
        iconClassName: "text-white",
      },
      {
        name: "OpenRouter",
        icon: "simple-icons:openrouter",
        iconClassName: "text-white",
      },
      {
        name: "Vercel AI SDK",
        icon: "simple-icons:vercel",
        iconClassName: "text-white",
      },
      {
        name: "RAG & Vector Search",
        icon: "mdi:file-search-outline",
        iconClassName: "text-white",
      },
      {
        name: "Embeddings",
        icon: "mdi:graph-outline",
        iconClassName: "text-white",
      },
      {
        name: "Prompt Engineering",
        icon: "mdi:message-cog-outline",
        iconClassName: "text-white",
      },
      {
        name: "AI Chatbots",
        icon: "mdi:robot-outline",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Async & Job Queues",
    subtitle: "Background workers, retries, and webhook orchestration",
    skills: [
      { name: "Celery", icon: "simple-icons:celery" },
      { name: "Redis", icon: "logos:redis" },
      {
        name: "TaskIQ",
        icon: "mdi:lightning-bolt-outline",
        iconClassName: "text-white",
      },
      { name: "BullMQ", icon: "twemoji:ox" },
      {
        name: "Cron Jobs",
        icon: "mdi:clock-outline",
        iconClassName: "text-white",
      },
      {
        name: "Background Workers",
        icon: "mdi:cogs",
        iconClassName: "text-white",
      },
      {
        name: "Idempotency & Retries",
        icon: "mdi:refresh",
        iconClassName: "text-white",
      },
      { name: "Webhooks", icon: "mdi:webhook", iconClassName: "text-white" },
    ],
  },
  {
    title: "Real-Time Systems",
    subtitle: "Live updates over sockets, streams, and pub/sub",
    skills: [
      {
        name: "WebSockets",
        icon: "mdi:swap-horizontal",
        iconClassName: "text-white",
      },
      {
        name: "Socket.IO",
        icon: "simple-icons:socketdotio",
        iconClassName: "text-white",
      },
      {
        name: "Django Channels",
        icon: "mdi:broadcast",
        iconClassName: "text-white",
      },
      {
        name: "Server-Sent Events",
        icon: "mdi:access-point",
        iconClassName: "text-white",
      },
      { name: "Firebase Firestore", icon: "logos:firebase" },
      {
        name: "Stream Chat",
        icon: "mdi:message-text-outline",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Databases & Storage",
    subtitle: "Relational, document, cache, and search layers",
    skills: [
      { name: "PostgreSQL", icon: "logos:postgresql" },
      { name: "MongoDB", icon: "logos:mongodb-icon" },
      { name: "Redis", icon: "logos:redis" },
      { name: "Supabase", icon: "logos:supabase-icon" },
      { name: "Firebase", icon: "logos:firebase" },
      { name: "NeonDB", icon: "simple-icons:neon", iconClassName: "text-white" },
      {
        name: "SQLite",
        icon: "simple-icons:sqlite",
        iconClassName: "text-white",
      },
      { name: "Typesense", icon: "mdi:magnify", iconClassName: "text-white" },
    ],
  },
  {
    title: "REST API Design",
    subtitle: "Auth, validation, and fault-tolerant integrations",
    skills: [
      { name: "RESTful APIs", icon: "mdi:api", iconClassName: "text-white" },
      {
        name: "JWT",
        icon: "simple-icons:jsonwebtokens",
        iconClassName: "text-white",
      },
      {
        name: "OAuth",
        icon: "mdi:shield-lock-outline",
        iconClassName: "text-white",
      },
      { name: "Clerk", icon: "simple-icons:clerk", iconClassName: "text-white" },
      {
        name: "Rate Limiting",
        icon: "mdi:speedometer",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Payments & Integrations",
    subtitle: "Money movement and third-party platform plumbing",
    skills: [
      { name: "Stripe", icon: "logos:stripe" },
      {
        name: "Razorpay",
        icon: "simple-icons:razorpay",
        iconClassName: "text-white",
      },
      {
        name: "Dodo Payments",
        icon: "simple-icons:dodopayments",
        iconClassName: "text-white",
      },
      {
        name: "Plaid",
        icon: "mdi:bank-outline",
        iconClassName: "text-white",
      },
      {
        name: "Sportmonks",
        icon: "mdi:soccer",
        iconClassName: "text-white",
      },
      {
        name: "DocuSeal",
        icon: "mdi:file-sign",
        iconClassName: "text-white",
      },
      {
        name: "Cal.com",
        icon: "simple-icons:caldotcom",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Cloud & DevOps",
    subtitle: "Shipping and operating apps across cloud platforms",
    skills: [
      { name: "AWS (EC2 · S3 · RDS)", icon: "logos:aws" },
      {
        name: "Vercel",
        icon: "simple-icons:vercel",
        iconClassName: "text-white",
      },
      { name: "Cloudflare", icon: "logos:cloudflare-icon" },
      {
        name: "Coolify",
        icon: "simple-icons:coolify",
        iconClassName: "text-white",
      },
      {
        name: "Render",
        icon: "simple-icons:render",
        iconClassName: "text-white",
      },
      { name: "Netlify", icon: "logos:netlify-icon" },
      { name: "Firebase Hosting", icon: "logos:firebase" },
      {
        name: "SSH Tunneling",
        icon: "mdi:console",
        iconClassName: "text-white",
      },
    ],
  },
  {
    title: "Tools & Practices",
    subtitle: "Delivery workflow, testing, and collaboration",
    skills: [
      { name: "Git", icon: "logos:git-icon" },
      { name: "GitHub", icon: "mdi:github", iconClassName: "text-white" },
      { name: "Jira", icon: "logos:jira" },
      { name: "Playwright", icon: "logos:playwright" },
      { name: "Postman", icon: "logos:postman-icon" },
      {
        name: "Agile / Scrum",
        icon: "mdi:account-group",
        iconClassName: "text-white",
      },
      {
        name: "Code Review",
        icon: "mdi:code-tags-check",
        iconClassName: "text-white",
      },
    ],
  },
];
export const projects = [
  {
    id: 0,
    name: "Pannly",
    description:
      "A startup-idea marketplace that mines real pain points from Reddit and Hacker News, scores them with an LLM, clusters them using pgvector embeddings, and publishes evidence-backed idea briefs — unlockable for $3, refunded automatically when the buyer ships within 30 days.",
    liveLink: "https://pannly.getrevlio.com/",
    githubLink: null,
    image: "/assets/projects/pannly.png",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [
      { id: 1, name: "FastAPI" },
      { id: 2, name: "Next.js" },
      { id: 3, name: "PostgreSQL" },
      { id: 4, name: "pgvector" },
      { id: 5, name: "Redis" },
      { id: 6, name: "OpenRouter" },
      { id: 7, name: "Dodo Payments" },
    ],
  },
  {
    id: 1,
    name: "SaaS Guard",
    description:
      "A centralized entitlement and permission management system for SaaS applications, handling feature access, roles, usage limits, and user-level overrides without hard-coded logic.",
    liveLink: "https://saasguard.rohitbuilds.tech/",
    githubLink: "https://github.com/rohit-jsfreaky/SaasGuard-frontend",
    image: "/assets/projects/saasguard.png",
    bgImage: "/assets/backgrounds/table.jpg",
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "TypeScript" },
      { id: 3, name: "Node.js" },
      { id: 4, name: "Express.js" },
      { id: 5, name: "PostgreSQL" },
      { id: 6, name: "Redis" },
      { id: 7, name: "Tailwind CSS" },
      { id: 8, name: "shadcn/ui" },
    ],
  },
  {
    id: 2,
    name: "Vouchley",
    description:
      "A real-time signup verification API for SaaS — five signal checks (email syntax, MX records, disposable domains, domain age, IP risk) run in parallel and merge into a 0–100 trust score with an approve/review/block recommendation, at p95 under 1.5 seconds.",
    liveLink: "https://vouchley.getrevlio.com/",
    githubLink: null,
    image: "/assets/projects/vouchley.png",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "FastAPI" },
      { id: 2, name: "Next.js" },
      { id: 3, name: "PostgreSQL" },
      { id: 4, name: "Redis" },
      { id: 5, name: "OpenRouter" },
      { id: 6, name: "IPQualityScore" },
      { id: 7, name: "Dodo Payments" },
    ],
  },
  {
    id: 3,
    name: "Skill Arena",
    description:
      "An online Esport Tournament Management System with team registrations, match scheduling, and real-time score updates.",
    liveLink: "https://eskillarena.in/",
    githubLink: null,
    image: "/assets/projects/skill-arena.png",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Express.js" },
      { id: 4, name: "Typescript" },
      { id: 5, name: "Shad cn" },
      { id: 6, name: "PostgreSQL" },
      { id: 7, name: "Razorpay" },
    ],
  },
  {
    id: 4,
    name: "Csv Editor",
    description:
      "This project is a robust CSV management platform that combines dynamic table editing, cloud storage with AWS S3, and secure authentication to deliver a seamless and user-friendly experience for managing and editing CSV files.",
    liveLink: "https://csv-editor-steel.vercel.app/",
    githubLink: "https://github.com/rohit-jsfreaky/Csv-Editor",
    image: "/assets/projects/cvs-editor.png",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Aws S3" },
      { id: 3, name: "Shad cn" },
      { id: 4, name: "Clerk" },
      { id: 5, name: "Tailwind CSS" },
      { id: 6, name: "Next Api" },
    ],
  },
  {
    id: 5,
    name: "Ai Mock Interview",
    description:
      "Built an AI-powered mock interview platform with Next.js, Drizzle ORM, and NeonDB, enhancing user preparation by 80%. Integrated Gemini API for tailored questions and Clerk for secure authentication, ensuring efficiency and scalability.",
    liveLink: "https://ai-mock-interview-iota-blush.vercel.app/",
    githubLink: "https://github.com/rohit-jsfreaky/Ai-mock-interview",
    image: "/assets/projects/ai-interview.png",
    bgImage: "/assets/backgrounds/map.jpg",
    frameworks: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Drizzle ORM" },
      { id: 3, name: "Tailwind CSS" },
      { id: 4, name: "NeonDB" },
    ],
  },
  {
    id: 6,
    name: "Ai Resume Builder",
    description:
      "I've developed an AI-powered resume builder using React, Node.js, and MongoDB, featuring AI-driven suggestions via Gemini API and secure authentication with Clerk",
    liveLink: null,
    githubLink: "https://github.com/rohit-jsfreaky/resume-builder-ai",
    image: "/assets/projects/resume.png",
    bgImage: "/assets/backgrounds/poster.jpg",
    frameworks: [
      { id: 1, name: "React.js" },
      { id: 2, name: "Mongo DB" },
      { id: 3, name: "Tailwind Css" },
      { id: 4, name: "Node.js" },
      { id: 5, name: "Express.js" },
    ],
  },
  {
    id: 7,
    name: "Job Portal",
    description:
      "Developed a job portal using React, Node.js, and MongoDB. Features include secure authentication, job postings, and application management, bridging the gap between students andemployers.",
    liveLink: null,
    githubLink: "https://github.com/rohit-jsfreaky/job-portal",
    image: "/assets/projects/job-portal.jpg",
    bgImage: "/assets/backgrounds/table.jpg",
    frameworks: [
      { id: 1, name: "React.js" },
      { id: 2, name: "Mongo DB" },
      { id: 3, name: "Tailwind Css" },
      { id: 4, name: "Node.js" },
      { id: 5, name: "Express.js" },
    ],
  },
];
export const companyProjects = [
  {
    id: 1,
    name: "TransferPitch",
    company: "Techorigins",
    role: "Full-Stack Engineer",
    description:
      "A B2B marketplace for football player transfers — clubs post tenders, agents pitch their players, and deals close in-app through chat, video meetings, and contract signing. Player data is aggregated from four providers (Wyscout, SportMonks, TheSports, Transfermarkt).",
    contributions: [
      "Optimized the transfers list endpoint from ~5 minutes to under 1 second using query projection, a generated sort column, and three-tier Redis caching",
      "Deduplicated roughly a million player records across 4 data providers with pg_trgm trigram and composite indexes",
      "Built real-time in-app notifications over Django Channels with a Redis channel layer",
      "Built 8 secured backend endpoints powering a WhatsApp bot that creates clubs, accounts, and tenders entirely via chat",
    ],
    liveLink: "https://dashboard.transferpitch.com/",
    image: "/assets/projects/transferpitch.png",
    bgImage: "/assets/backgrounds/map.jpg",
    techStack: [
      "Django",
      "DRF",
      "PostgreSQL",
      "Celery",
      "Redis",
      "Django Channels",
      "React",
      "Tailwind CSS",
    ],
  },
  {
    id: 2,
    name: "SquareOne",
    company: "Techorigins",
    role: "Full-Stack Engineer",
    description:
      "An AI bookkeeping SaaS for US creative professionals — connects banks via Plaid and categorizes a full year of transactions into IRS Schedule C categories with an LLM, turning tax prep into a one-hour guided review instead of a spreadsheet marathon.",
    contributions: [
      "Engineered a structured categorization prompt with pre-LLM heuristics, lifting accuracy from ~70% to 90%+ on a labeled test set",
      "Built live categorization progress over Server-Sent Events backed by Redis pub/sub",
      "Designed Plaid reconnect dedup with canonical account keys and transaction fingerprints so reconnecting a bank never duplicates history",
      "Gated AI spend behind Stripe payment with webhook-driven job queueing",
    ],
    liveLink: "https://trysquareone.com/",
    image: "/assets/projects/cuiq.png",
    bgImage: "/assets/backgrounds/poster.jpg",
    techStack: [
      "Django",
      "DRF",
      "Celery",
      "Redis",
      "Plaid",
      "Stripe",
      "OpenRouter",
      "React",
    ],
  },
  {
    id: 3,
    name: "StudioMode.ai",
    company: "Techorigins",
    role: "Full-Stack Engineer",
    description:
      "An AI product-photography studio for e-commerce — sellers upload one product photo and generate studio-grade scene variants, fashion try-ons, and short product videos, on a credit-based subscription with a Shopify bridge to the same engine.",
    contributions: [
      "Built the generation-job pipeline — queue, worker claim via SELECT FOR UPDATE SKIP LOCKED, dispatch to fal.ai with idempotency keys, and webhook-driven completion",
      "Designed the billing core: an append-only credit ledger with server-side plan-limit enforcement, so the frontend can't smuggle a bigger job through the queue",
      "Hand-rolled an OAuth2 / OpenID Connect provider plus an MCP server and agent-discovery surfaces, so AI agents can find and authenticate against the API",
      "Built the Next.js studio frontend and a programmatic-SEO marketing site",
    ],
    liveLink: "https://studiomode.ai/",
    image: "/assets/projects/studiomode.png",
    bgImage: "/assets/backgrounds/blanket.jpg",
    techStack: [
      "FastAPI",
      "PostgreSQL",
      "TaskIQ",
      "AWS S3",
      "fal.ai",
      "OpenRouter",
      "Next.js",
      "Dodo Payments",
    ],
  },
  {
    id: 4,
    name: "Clarix",
    company: "Techorigins",
    role: "Full-Stack Engineer",
    description:
      "A multi-tenant project and task management platform for agencies — org, teams, projects, Kanban boards, subtasks, @mention comments, and real-time notifications, with two-way Slack sync and Fathom AI meeting notes that become tasks.",
    contributions: [
      "Designed the multi-tenant row-level-security model — every table gated by SECURITY DEFINER helpers, with a strict guest role so external clients only ever see their one project",
      "Built the Kanban and grouped-list views on dnd-kit with optimistic React Query updates — dropping a card into a column also adopts its status",
      "Built 12 Deno edge functions powering email invitations, two-way Slack sync (DMs, slash commands, thread replies), and Fathom meeting-notes-to-tasks",
      "Test-first discipline across the stack: pgTAP for every RLS policy, Vitest for hooks, Deno tests for edge functions, Playwright for cross-feature journeys",
    ],
    liveLink: "https://clarix.app/",
    image: "/assets/projects/clarix.png",
    bgImage: "/assets/backgrounds/curtains.jpg",
    techStack: [
      "React",
      "TypeScript",
      "Supabase",
      "PostgreSQL RLS",
      "Deno Edge Functions",
      "Slack API",
      "pgTAP",
      "Playwright",
    ],
  },
  {
    id: 5,
    name: "Mailvalid",
    company: "Techorigins",
    role: "Full-Stack Engineer",
    description:
      "A production email-verification SaaS — give it an email or a list, and it tells you whether the mailbox is real and safe to send to, with a 0–100 confidence score. Live at mailvalid.io with credit-based billing.",
    contributions: [
      "Built the 4-layer verification engine — syntax, MX lookup, provider-aware SMTP probing with greylist retries, and confidence-scored classification",
      "Bulk verification on TaskIQ workers with credits reserved up front and HMAC-signed completion webhooks with exponential-backoff retries",
      "Dodo subscription billing with a capped dunning flow — failed renewals trigger up to 3 recovery emails driven by a daily cron, surfaced in an admin Payment Alerts view",
      "Shipped an MCP server (npm: @mailvalid/mcp) so AI agents like Claude and Cursor can verify emails as tools",
    ],
    liveLink: "https://mailvalid.io/",
    image: "/assets/projects/mailvalid.png",
    bgImage: "/assets/backgrounds/table.jpg",
    techStack: [
      "FastAPI",
      "PostgreSQL",
      "Redis",
      "TaskIQ",
      "SQLAlchemy",
      "Dodo Payments",
      "MCP",
      "AWS SES",
    ],
  },
];
export const npmPackages = [
  {
    id: 1,
    name: "error-less",
    tagline: "The 'Viral' Star",
    emoji: "🌟",
    problem: "Standard Node.js stack traces are noisy, monochromatic, and force developers to manually hunt for line numbers.",
    solution: "A zero-config library that intercepts V8 stack traces to print beautiful, syntax-highlighted code frames directly in the terminal, complete with AI-style troubleshooting tips.",
    features: ["Visual Context - Displays exact 5 lines of code surrounding error", "Smart Suggestions - Auto-generates tips based on error types", "Lightweight - < 100kB packed size with no heavy dependencies"],
    techStack: ["TypeScript", "V8 Stack Trace API", "AST Parsing", "Source Maps"],
    image: "/assets/projects/error-less.png",
    npmLink: "https://www.npmjs.com/package/error-less",
    githubLink: "https://github.com/rohit-jsfreaky/error-less",
  },
  {
    id: 2,
    name: "cron-safe",
    tagline: "The 'Reliability' Engine",
    emoji: "🛡️",
    problem: "Standard cron jobs fail silently, overlap during long tasks, and vanish during server restarts.",
    solution: "A drop-in wrapper for `node-cron` that brings enterprise reliability features—usually found in Redis/BullMQ—to simple file-based setups.",
    features: ["Idempotency & Retries - Automatic exponential backoff", "Overlap Prevention - Atomic locking prevents zombie processes", "Persistence - SQLite-backed job history survives restarts"],
    techStack: ["TypeScript", "SQLite (WAL Mode)", "Event Emitters", "Process Locking"],
    image: "/assets/projects/cron-safe.png",
    npmLink: "https://www.npmjs.com/package/cron-safe",
    githubLink: "https://github.com/rohit-jsfreaky/cron-safe",
  },
  {
    id: 3,
    name: "node-network-tab",
    tagline: "The 'Internal' Tool",
    emoji: "📡",
    problem: "Debugging HTTP requests on a headless server usually involves messy `console.log` spam.",
    solution: "A TUI (Terminal User Interface) that visualizes outgoing network traffic in real-time, allowing developers to inspect headers, payloads, and timings without leaving the CLI.",
    features: ["Zero-Latency - Monkey-patches Node.js http/https modules", "Interactive TUI - Scrollable request history built with Ink"],
    techStack: ["React (Ink)", "Monkey Patching", "Node.js Streams", "Proxy Patterns"],
    image: "/assets/projects/node-network-tab.png",
    npmLink: "https://www.npmjs.com/package/node-network-tab",
    githubLink: "https://github.com/rohit-jsfreaky/node-network-tab",
  },
  {
    id: 4,
    name: "express-rate-limit-redis-slim",
    tagline: "The 'Performance' Optimizer",
    emoji: "⚡",
    problem: "Existing Redis rate-limiters were bloated with dependencies, slowing down high-throughput microservices.",
    solution: "A hyper-optimized middleware that uses raw Redis atomic commands (Lua scripts) to handle thousands of requests per second with minimal CPU usage.",
    features: ["60% Smaller - Stripped of all non-essential dependencies", "Atomic Precision - Prevents race conditions in distributed systems"],
    techStack: ["Redis (Lua Scripting)", "Express Middleware", "Distributed Systems"],
    image: "/assets/projects/express-rate-limit-redis-slim.png",
    npmLink: "https://www.npmjs.com/package/express-rate-limit-redis-slim",
    githubLink: "https://github.com/rohit-jsfreaky/express-rate-limit-redis-slim",
  },
  {
    id: 5,
    name: "zod-mock-data",
    tagline: "The 'DX' Booster",
    emoji: "🛠️",
    problem: "Writing mock data for tests is tedious and often drifts out of sync with actual Type definitions.",
    solution: "A utility that recursively parses Zod schemas to generate realistic, randomized test fixtures automatically.",
    features: ["Single Source of Truth - Zod schema defines validation & mock data", "Complex Types - Handles nested objects, arrays, optional fields"],
    techStack: ["TypeScript", "Zod", "Recursive Algorithms", "Generics"],
    image: "/assets/projects/zod-to-mock-data.png",
    npmLink: "https://www.npmjs.com/package/zod-mock-data",
    githubLink: "https://github.com/rohit-jsfreaky/zod-mock-data",
  }
];
export const socials = [
  {
    name: "Whatsapp",
    href: "https://wa.me/916397883500?text=Hi%20Rohit%2C%20I%20saw%20your%20portfolio",
  },
  { name: "LinkedIn", href: "https://www.linkedin.com/in/r2609/" },
  { name: "GitHub", href: "https://github.com/rohit-jsfreaky" },
];

export const experiences = [
  {
    title: "Full Stack Engineer",
    company_name: "Techorigins",
    icon: "/assets/company/techorigins.jpg",
    iconBg: "#383E56",
    date: "July 2025 - Present",
    points: [
      "Developed and optimized responsive UIs with React.js, improving page load performance by 30% and enhancing user retention",
      "Implemented reusable component libraries with TypeScript and Tailwind CSS, reducing development time by 25% across projects.",
      "Collaborated with backend teams to integrate REST and GraphQL APIs, cutting integration issues by 40%",
      "Improved accessibility and SEO scores of web apps, achieving 95+ Lighthouse scores and boosting organic traffic",
    ],
  },
  {
    title: "React.js Developer",
    company_name: "Revenza Tech",
    icon: "/assets/company/revenza.jpg",
    iconBg: "#383E56",
    date: "May 2025 - July 2025",
    points: [
      "Developed and deployed custom ERP systems, streamlining workflows and reducing manual processing time by 30%.",
      "Built responsive web applications that improved user engagement and led to a 25% faster load time across platforms.",
      "Delivered cross-platform mobile apps that enhanced customer reach, achieving 40% higher user adoption within the first release cycle.",
      "Managed full-stack development independently, completing projects 20% ahead of deadlines while ensuring 99.9% uptime",
    ],
  },
  {
    title: "Software Developer Engineer intern (React-native)",
    company_name: "CoRider",
    icon: "/assets/company/corider.jpg",
    iconBg: "#383E56",
    date: "Jan 2025 - May 2025",
    points: [
      "Improved UI Performance by 40% – Optimized re-renders and data flow to enhance app responsiveness and user experience.",
      "Integrated 100% Functional Features – Successfully implemented Google APIs, user KYC verification, and real-time chat, ensuring seamless interactions.",
      "Ensured 99.9% Uptime on Both Platforms – Fixed Android and iOS-specific issues, enabling smooth cross-platform functionality.",
      "Enhanced State Management by 60% – Optimized data handling for real-time updates, reducing lag and improving app efficiency.",
    ],
  },
  {
    title: "Software Developer intern",
    company_name: "Cogent Web Services",
    icon: "/assets/company/cogent.png",
    iconBg: "#383E56",
    date: "July 2024 - Dec 2024",
    points: [
      "Developed 5+ full-stack web applications using MERN stack and PostgreSQL, including complex platforms like an esports tournament management system with secure authentication, payment integration, and admin control.",
      "Engineered complete backend and frontend architecture for multiple client projects, handling RESTful APIs, responsive UI, and real-time data using React, Node.js, and Express.",
      "Built and deployed a cross-platform mobile application using React Native under NDA, integrating secure user flows, API consumption, and native device capabilities.",
      "Delivered production-ready solutions for businesses, from modern portfolio websites to scalable multi-user platforms, improving user engagement and functionality by 40%+.",
    ],
  },
  {
    title: "Mern Stack Developer intern",
    company_name: "Zidio Development",
    icon: "/assets/company/zidio.png",
    iconBg: "#383E56",
    date: "Apr 2024 - June 2024",
    points: [
      "Developed a full-stack AI-powered resume builder using React, Node.js, and MongoDB, integrating Gemini API for AI-driven suggestions and Clerk for secure authentication.",
      "Built a dynamic job portal using the MERN stack, implementing recruiter and student authentication, job posting features, and job application tracking.",
      "Utilized RESTful APIs to handle user authentication, job data retrieval, and secure communication between frontend and backend systems.",
      "Ensured seamless UI/UX with Tailwind CSS and Shadcn UI, improving user experience across devices while optimizing performance.",
    ],
  },
];
